version: "3.1"
services:
  solita-db:
    container_name: solita-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
      POSTGRES_DB: electricity
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5432:5432
  solita-api:
    container_name: solita-api
    image: solita-api:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_HTTP_PORTS:
    ports:
      - 5128:5128
  adminer:
    container_name: solita-adminer
    image: adminer
    restart: always
    ports:
      - 8088:8080
