version: "3.1"
services:
  solita-front:
    container_name: solita-front
    image: solita-front:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://localhost:8080
    ports:
      - 5173:5173

  solita-db:
    container_name: solita-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
      POSTGRES_DB: electricity
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5432:5432
  solita-api:
    container_name: solita-api
    image: solita-api:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      DOTNET_ENVIRONMENT: Docker
    ports:
      - 5128:5128
  adminer:
    container_name: solita-adminer
    image: adminer
    restart: always
    ports:
      - 8088:8080
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: proxy
    depends_on:
      - solita-front
      - solita-api
